apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: Karpenter-eks-devops-senior-20260520224506640100000012
  amiSelectorTerms:
    - alias: al2023@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-devops-senior
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-devops-senior