apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: Karpenter-eks-devops-senior-0dbc849696e89b7421273dd71e
  amiSelectorTerms:
    - alias: al2023@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-devops-senior
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-devops-senior